### ISSUE TITLE
Message isn't being set by default

### ISSUE THREAD

**Issue by rogeruiz** [MadcapJake/fly-notify#3]
The documentation gives an example to add options by passing in a `POJO` to the `notify` method.

``` js
   .notify({
      title: "Fly Default",
      message: "Completed default task", // This line in particular
      icon: "dev:code_badge"
    })
```

I didn't have any luck until I cracked open the code here, and saw the assignment order [here](https://github.com/MadcapJake/fly-notify/blob/master/index.js#L7-L13)

``` js
    notifier.notify(assign(options, { // `options` argument is first so it's content will be ovewritten.
      title: "Fly",
      message: "Task completed.",
      icon: options.icon
        ? devicon(options.icon)
        : path.join(__dirname, "fly-logo.png")
    }),
```

I'd like to submit a patch updating this. I know the project is pretty new so I wanted to make sure I wasn't stepping on any toes. Let me know and I'll submit a PR.

**Comment by MadcapJake** [comment]
No worries! No toes stepped on here! :stuck_out_tongue_closed_eyes:

**Comment by rogeruiz** [comment]
Cool. I'll submit this later tonight for review. thanks! :+1:
